### ISSUE TITLE
support generators?

### ISSUE THREAD

**Issue by tunnckoCore** [phated/async-done#21]
Add support to handle "end" of generators? e.g.

```js
var i = 10
function * success() {
  yield [i++]
  return i
}

function * failure() {
  yield [i++]
  throw new Error('boom')
  return i
}

asyncDone(success, function(err, res) {
  expect(res).to.equal(11);
});
asyncDone(failure, function(err, res) {
  expect(err).to.be.instanceof(Error);
});
```

**Comment by phated** [comment]
I'd be :+1: for this but is there a way to implement it that doesn't break back-compat with node 0.10?

**Comment by tunnckoCore** [comment]
Mm.. I think yes, I'll try.

**Comment by tunnckoCore** [comment]
Erm, wait, why not? I made it, actually. Check if given fn is generator, then pass it to `co.wrap()` and it transform the fn to regular function that return promise. Will only get the tests working on 0.10, lol

**Comment by phated** [comment]
I'd prefer for this module to not need external dependencies for completion support.  e.g. the promise implementation just checks for a `.then` method and RxJS just checks for a `.subscribe` method.  We brought in `end-of-stream` to normalize the behavior between streams1/2/3, child processes and event emitters.  What does `co.wrap` do internally and how do you check if something is a generator?

**Comment by phated** [comment]
Sidenote - I don't depend on TJ projects, so even if I was going to bring in a library to help out, it wouldn't be `co`

**Comment by tunnckoCore** [comment]
> Sidenote - I don't depend on TJ projects

Interesting. That community, hmm. Jon Schlinkert - Sinde Sorhus, phated - TJ. Lol, nothing serious, just kidding.

> I'd prefer for this module to not need external dependencies for completion support.

It wouldn't. It would be needed only for the tests. 
*btw, i cant realize why `gnode` not works (or i missing something), lol.*

> What does co.wrap do internally and how do you check if something is a generator?

It just would make it promise, so another code will still work and handle all the things.


its nothing more than, really

```js
  var d = domain.create();
  d.once('error', onError);

  if (isGeneratorFn(fn)) {
    fn = co.wrap(fn)
  }

  var domainBoundFn = d.bind(fn);
```

https://github.com/tunnckoCore/is-es6-generator-function

> so even if I was going to bring in a library to help out, it wouldn't be co

with what, then?

**Comment by tunnckoCore** [comment]
> Sidenote - I don't depend on TJ projects

Okey, its normal and understandable to everyone, but.. co is co, it is good thing. And yea, I'm thinking for something new like co - support regular and generator functions as input and return promise or callback style... e.g.

regular function to promise
```js
ko(function (next) {
  next(null, 123)
})
.then(function (res) {
  console.log(res)
  //=> 123
})
```

regular to callback
```js

ko(function (next) {
  next(null, 123)
})(function (err, res) {
  console.log(res)
  //=> 123
})
```

generator to callback
```js
var count = 10
ko(function * (next) {
  yield count++
  return count
})(function (err, res) {
  console.log(res)
  //=> 11
})
```
generator to promise
```js
var count = 10
ko(function * (next) {
  yield count++
  return count
})
.then(function (res) {
  console.log(res)
  //=> 11
})
```

**Comment by phated** [comment]
Hmm, I don't have much experience with these, but couldn't you just do (gulp example):

```js
gulp.task('default', ko(function * () { yield count++ }));
```

??

**Comment by tunnckoCore** [comment]
My latest comment and examples in it are just in my mind for new project like co/vo and without using them.

**Comment by tunnckoCore** [comment]
The problem because that I dont do the PR now is cuz can't run the test on node 0.10 lol, which actually will be job of the user that will use `async-done` in node 0.10, as it is job of the user that use co in node 0.10, and at all user that trying to use `generators` in 0.10.

**Comment by phated** [comment]
Travis currently runs on 0.10 *only*, this will be updated in the future, but should be enough to have things tested.

**Comment by tunnckoCore** [comment]
> Travis currently runs on 0.10 only

yea, noticed that

Haha, wait.. wait. We should not do anything than that. People now that generators are not supported in 0.10, so if they want ot run code in 0.10 that have generators they should search what to the to run it. It's not our job.

It's easy just to not run the generator tests on 0.10 and all is done. It would be enough to add notice that `async-done` support generators, but not in node 0.10, which is logical.

**Comment by tunnckoCore** [comment]
@TooTallNate help to run tests that use generators on 0.10? I tried with just

```js
require('gnode')
```
on top of the file containing that tests, but it continue to throw error for `Unexpected token *`

**Comment by phated** [comment]
in 0.10, I think you can use `--harmony` flag when starting node (not sure though).

Also, https://github.com/cujojs/when/blob/master/docs/api.md#es6-generators could probably be used in place of co.

**Comment by tunnckoCore** [comment]
> in 0.10, I think you can use

nope its for 0.11

i'll just try with mocha instead of lab, cuz im curious.

**Comment by tunnckoCore** [comment]
And why? When you can use 200 lines of code without any dependency, without any requirement of promise and have flexibility. That example of `when/generator` not looks good to me.

**Comment by phated** [comment]
@tunnckoCore your fork currently uses `co` which has a promise dependency.  I'm not sure where you are going with this?  I was suggesting an alternative to `co` that I trust as a dependency.  Anyway, I'm out for the night, so send a PR when you have something.

**Comment by tunnckoCore** [comment]
ha.. it seems travis or nvm drop support for < 1.0 ? lol this is from last hours.

`nvm ls-remote` locally dont list any lower than < 1.0 lol.

**Comment by tunnckoCore** [comment]
https://travis-ci.org/tunnckoCore/is-hexcolor
https://travis-ci.org/regexps/hex-color-regex
https://travis-ci.org/tunnckoCore/char-codes
https://travis-ci.org/jstransformers/boilerplate

try rebuild, hm.

**Comment by tunnckoCore** [comment]
ahh omg, nodejs.org is donw for 4 hours http://www.isitdownrightnow.com/nodejs.org.html

**Comment by tunnckoCore** [comment]
@phated what you mean with

> your fork currently uses co which has a promise dependency.

`co` dont have promise dependency and that is the problem, actually when I rethink it.

**Comment by tunnckoCore** [comment]
@phated okey i found workaround. But in that time found new bug, I'll open new PR in a bit.
