### ISSUE TITLE
failing child process, pass null to done

### ISSUE THREAD

**Issue by tunnckoCore** [phated/async-done#24]
I don't think this is correct.

example

```js
asyncDone(function () {
  return cp.spawn('not_existing_command', ['hello'])
}, function (err, res) {
  console.log(err, res)
  // err always `null`
})
```
it always pass the result of spawn to res, no matter it executes `echo hello` or not exising command.

Because this `onSuccess` in [index.js#L43](https://github.com/phated/async-done/blob/master/index.js#L43)

**Comment by phated** [comment]
The error events should still be caught by the domain.  Seems like a node bug?

**Comment by tunnckoCore** [comment]
> should still

yes, should, but not. And no, not works in any version of node/iojs from 3.2 to 0.10

**Comment by phated** [comment]
Can you please open something on one of the node projects and see if this is actually a bug within node?

**Comment by tunnckoCore** [comment]
Mm, okey, i'll check.

**Comment by tunnckoCore** [comment]
Gotcha! It have logic. We should pass directly `done` to `end-of-stream`, not `onSuccess` so it does the things correctly. So, I'll PR.

**Comment by tunnckoCore** [comment]
Sorry for the reference noise.
