### ISSUE TITLE
allow passing options to `end-of-stream`?

### ISSUE THREAD

**Issue by tunnckoCore** [phated/async-done#26]
Allow modify/extend options that have been passed to `eos`?

**Comment by phated** [comment]
I thought about this but I think it clutters the API if put in the function signature.  Maybe it could be attached as a static property to the exported function?  That seems worse.  I could create a submodule that exports the config as an object and it could be altered by a consuming library... Hmm.

**Comment by tunnckoCore** [comment]
> it clutters the API if put in the function signature.

I don't think so, it's natural. And it's not hard to be implemented. 

> That seems worse.

Everything different from optional `options` object which would be able to be extended/modified object, seems worse to me. lol.

**Comment by phated** [comment]
I don't think I am going to expose these.  This is an opinionated module and I might switch out `end-of-stream` in the future.  I don't want to adopt their API into mine.
